#!/usr/bin/env bun
import { mkdirSync, statSync } from "node:fs";
import { dirname, join, resolve } from "node:path";

const REPO_ROOT = resolve(import.meta.dir, "../..");
const CORE_MIGRATION_DIR = join(REPO_ROOT, "packages/core/migration");
const STUDIO_DIST_DIR = join(REPO_ROOT, "packages/studio/dist/client");
const CORE_OUTPUT = join(REPO_ROOT, "packages/core/src/generated/embedded-migrations.ts");
const STUDIO_OUTPUT = join(REPO_ROOT, "packages/studio/src/server/generated/embedded-assets.ts");
const CLEAN = Bun.argv.includes("--clean");

function toPosixPath(path: string): string {
  return path.split("\\").join("/");
}

function sha256Hex(value: string): string {
  return new Bun.CryptoHasher("sha256").update(value).digest("hex");
}

async function listFiles(cwd: string, pattern: string): Promise<string[]> {
  const files: string[] = [];
  for await (const entry of new Bun.Glob(pattern).scan({ cwd })) {
    const relativePath = toPosixPath(entry);
    const stat = statSync(join(cwd, relativePath), { throwIfNoEntry: false });
    if (stat?.isFile()) {
      files.push(relativePath);
    }
  }
  files.sort((a, b) => a.localeCompare(b));
  return files;
}

async function writeIfChanged(path: string, content: string): Promise<void> {
  mkdirSync(dirname(path), { recursive: true });
  const currentStat = statSync(path, { throwIfNoEntry: false });
  if (currentStat?.isFile()) {
    const current = await Bun.file(path).text();
    if (current === content) {
      return;
    }
  }
  await Bun.write(path, content);
}

async function deleteIfExists(path: string): Promise<void> {
  try {
    await Bun.file(path).delete();
  } catch (error) {
    if (error instanceof Error && "code" in error && error.code === "ENOENT") {
      return;
    }
    throw error;
  }
}

async function renderEmbeddedMigrationsModule(): Promise<string> {
  const migrationFiles = await listFiles(CORE_MIGRATION_DIR, "*.sql");
  const imports: string[] = [];
  const rows: string[] = [];

  for (const [index, file] of migrationFiles.entries()) {
    const variable = `m${index}`;
    const sql = await Bun.file(join(CORE_MIGRATION_DIR, file)).text();
    imports.push(`import ${variable} from ${JSON.stringify(`../../migration/${file}`)} with { type: "text" };`);
    rows.push(`  { id: ${JSON.stringify(file.slice(0, -4))}, hash: ${JSON.stringify(sha256Hex(sql))}, sql: ${variable} },`);
  }

  const lines = [
    "// Generated by scripts/release/gen-embedded-modules.ts. Do not edit.",
    ...imports,
    "",
    "export const ENGINE_MIGRATIONS = [",
    ...rows,
    "] as const;",
    "",
  ];
  return lines.join("\n");
}

async function renderEmbeddedAssetsModule(): Promise<string> {
  const distStat = statSync(STUDIO_DIST_DIR, { throwIfNoEntry: false });
  const assetFiles = distStat?.isDirectory() ? await listFiles(STUDIO_DIST_DIR, "**/*") : [];
  const imports: string[] = [];
  const rows: string[] = [];

  for (const [index, file] of assetFiles.entries()) {
    const variable = `a${index}`;
    const routePath = file === "index.html" ? "/" : `/${toPosixPath(file)}`;
    imports.push(`import ${variable} from ${JSON.stringify(`../../../dist/client/${file}`)} with { type: "file" };`);
    rows.push(`  [${JSON.stringify(routePath)}, ${variable}],`);
  }

  const lines = [
    "// Generated by scripts/release/gen-embedded-modules.ts. Do not edit.",
    ...imports,
    "",
    "export const STUDIO_ASSET_PATHS = new Map<string, string>([",
    ...rows,
    "]);",
    "",
  ];
  return lines.join("\n");
}

if (CLEAN) {
  await Promise.all([deleteIfExists(CORE_OUTPUT), deleteIfExists(STUDIO_OUTPUT)]);
} else {
  const [migrationsModule, assetsModule] = await Promise.all([
    renderEmbeddedMigrationsModule(),
    renderEmbeddedAssetsModule(),
  ]);

  await Promise.all([
    writeIfChanged(CORE_OUTPUT, migrationsModule),
    writeIfChanged(STUDIO_OUTPUT, assetsModule),
  ]);
}
